version: "3.1"
services:
  mongodb:
    image: mongo:4.4.1
    container_name: "mongodb"
    hostname: localhost
    ports:
    - 27017:27017
    restart: always
  app:
    build: .
    #image: yinkin/elderservice
    restart: always
    ports:
    - 8080:8080
    depends_on:
    - mongodb